In [2]:
import pandas

data = pandas.read_csv("../data/owls.csv")

In [42]:
from sklearn.svm import LinearSVC
import numpy as np

total = len(data)
split = int(np.floor(total * 0.6))
samples = np.arange(total)
np.random.shuffle(samples)

training = samples[:split]
testing = samples[split:]

svm = LinearSVC()

reduced =  svm.fit_transform(data.iloc[training, :-1], data.iloc[training, -1])

for i, x in enumerate(reduced):
    print "%r -> %r" % (data.iloc[i, :-1].values, x)

predictions = svm.predict(data.iloc[testing, :-1])
actuals = data.iloc[testing, -1]

for i, prediction in enumerate(predictions):
    actual = actuals.iloc[i]
    
    print "%s \t==\t%s \t(%r)" % (actual, prediction, actual == prediction)
    

array([3.0, 5.0, 1.6000000000000001, 0.20000000000000001], dtype=object) -> array([ 4.6,  1.5])
array([3.2000000000000002, 4.7000000000000002, 1.6000000000000001,
       0.20000000000000001], dtype=object) -> array([ 3.8,  1.1])
array([3.3999999999999999, 4.5999999999999996, 1.3999999999999999,
       0.29999999999999999], dtype=object) -> array([ 4.5,  1.5])
array([3.6000000000000001, 5.0, 1.3999999999999999, 0.20000000000000001], dtype=object) -> array([ 6.6,  2.1])
array([4.0999999999999996, 5.2000000000000002, 1.5, 0.10000000000000001], dtype=object) -> array([ 1.6,  0.6])
array([3.0, 4.9000000000000004, 1.3999999999999999, 0.20000000000000001], dtype=object) -> array([ 4.7,  1.5])
array([3.2999999999999998, 5.0999999999999996, 1.7, 0.5], dtype=object) -> array([ 5.4,  2.1])
array([3.3999999999999999, 4.7999999999999998, 1.6000000000000001,
       0.20000000000000001], dtype=object) -> array([ 4.2,  1.2])
array([3.7000000000000002, 5.0999999999999996, 1.5, 0.40000000000000002], dty